### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by manbill** [irvine1231/flutter_app_installer#1]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_app_installer' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by irvine1231** [comment]
Seems like the package gradle `ext.kotlin_version` for flutter need to be upgrade.

I will try to upgrade the version this weekend.

**Comment by manbill** [comment]
thank you very much！




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irvine1231/flutter_app_installer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月21日(星期三) 中午1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [irvine1231/flutter_app_installer] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. (Issue #1)





 
Seems like the package gradle ext.kotlin_version for flutter need to be upgrade.
 
I will try to upgrade the version this weekend.

**Comment by irvine1231** [comment]
@manbill 
I have upgrade the flutter, gradle, and kotlin version for the package, and release version 1.0.0.
Due to the upgrade, all methods have been change to non-static method, you might need to change your application code.

**Comment by manbill** [comment]
Thank you very much for taking the time to upgrade the plugin code. In many of my recent Flutter projects, plugin methods were defined with 'static' keyword because it was more convenient to use in this way. May I ask why you removed the 'static' keyword this time? Is there any potential impact of using 'static' methods on the code or project?




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irvine1231/flutter_app_installer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月24日(星期六) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [irvine1231/flutter_app_installer] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. (Issue #1)





 
@manbill
 I have upgrade the flutter, gradle, and kotlin version for the package, and release version 1.0.0.
 Due to the upgrade, all methods have been change to non-static method, you might need to change your application code.

**Comment by irvine1231** [comment]
I create a new flutter plugin project and see the current plugin project is using non-static method implementation by default.

So I follow the default implementation and upgrade the project to use the non-static method.
Sorry for the inconvenient, but it would be easier for me to maintain if I follow the default implementation.

**Comment by manbill** [comment]
thanks ！




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "irvine1231/flutter_app_installer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月25日(星期天) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [irvine1231/flutter_app_installer] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. (Issue #1)





 
I create a new flutter plugin project and see the current plugin project is using non-static method implementation by default.
 
So I follow the default implementation and upgrade the project to use the non-static method.
 Sorry for the inconvenient, but it would be easier for me to maintain if I follow the default implementation.
