### ISSUE TITLE
In-App update

### ISSUE THREAD

**Issue by GilmarCoop** [irvine1231/flutter_app_installer#3]
I'm trying to make an In-App update using this package, but it doesn't seem to be working.
The file is downloaded and saved locally correctly, but it doesn't seem to uninstall and reinstall the app.

Is it possible, by the way?

Here's my code:

```
Future<void> downloadAppVersion(int code) async {
  var response = await http.get(
    Uri.parse('${HttpConstants.API}appVersions/download?versionCode=$code'),
  );

  if (response.statusCode >= 400) {
    ErrorMessage(response.body).show();
    return;
  }

  var output = await getExternalStorageDirectory();
  File file = File('${output?.uri.toFilePath()}/v-$code.apk');
  await file.writeAsBytes(response.bodyBytes);

  final FlutterAppInstaller flutterAppInstaller = FlutterAppInstaller();
  await flutterAppInstaller.installApk(filePath: file.path);
}
```

**Comment by irvine1231** [comment]
It should be working, you can check the example of the plugin.

The example is doing a self-updating from version 1.0.0 (6) to version 1.0.0 (7).

Could you please check if the `File file = File('${output?.uri.toFilePath()}/v-$code.apk');` file equals to the return value of the `await file.writeAsBytes(response.bodyBytes);`?
writeAsBytes method will return a File object, and in the example I am writing it like this, not sure if it will make the result different.

```
  Future<void> initTestApkFile() async {
    const filename = 'test-install.apk';
    var bytes = await rootBundle.load("assets/$filename");
    String path = "${(await getExternalStorageDirectory())!.uri.toFilePath()}$filename";

    final buffer = bytes.buffer;
    _testInstallApk = await File(path).writeAsBytes(
      buffer.asUint8List(
        bytes.offsetInBytes,
        bytes.lengthInBytes,
      ),
    );
  }
```

Also please check if you have given your app installation permission in the [Android Manifest](https://github.com/irvine1231/flutter_app_installer/blob/master/example/android/app/src/main/AndroidManifest.xml).

**Comment by GilmarCoop** [comment]
Hey, sorry for the delay.

My mistake. The problem was related to a signing key mismatch.
Thank you, anyway!
